headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/mac/Documents/swariya-weddings-complete-project"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]